<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>fr.iut-tlse3.fr</groupId>
  <artifactId>programmation_SAE_S2-01_2026_GA_7</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>

  <dependencies>

    <!-- @Responsable : installe dans ~/.m2 via l'etape 3 du README -->
    <dependency>
      <groupId>fr.iut-tlse3.fr</groupId>
      <artifactId>annotation-lib</artifactId>
      <version>0.0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <!-- Lecture/ecriture JSON : telecharge automatiquement par Maven -->
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20210307</version>
    </dependency>

    <!-- JUnit 4 pour les tests -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>fr.iut-tlse3.fr</groupId>
              <artifactId>annotation-lib</artifactId>
              <version>0.0.1-SNAPSHOT</version>
            </path>
          </annotationProcessorPaths>
          <!-- Phase "sources" : rapport nommé <artifactId>-sources.xlsx -->
          <compilerArgs>
            <arg>-Aproject.artifactId=${project.artifactId}</arg>
            <arg>-Aphase=sources</arg>
          </compilerArgs>
        </configuration>
        <executions>
          <execution>
            <id>process-test-sources</id>
            <goals><goal>testCompile</goal></goals>
            <configuration>
              <annotationProcessorPaths>
                <path>
                  <groupId>fr.iut-tlse3.fr</groupId>
                  <artifactId>annotation-lib</artifactId>
                  <version>0.0.1-SNAPSHOT</version>
                </path>
              </annotationProcessorPaths>
              <!-- Phase "tests" : rapport nommé <artifactId>-tests.xlsx -->
              <compilerArgs>
                <arg>-Aproject.artifactId=${project.artifactId}</arg>
                <arg>-Aphase=tests</arg>
              </compilerArgs>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
